version: '3.8'

networks:
  loki:
    driver: bridge

services:
  api:
    image: fabricioveronez/pedelogo-catalogo:v1
    ports:
      - "8080:80"
    networks:
      - loki
    volumes:
      - "./logs/api:/log"
    environment:
      Mongo__Host: mongodb
      Mongo__User: mongouser
      Mongo__Password: mongopwd
      Mongo__Port: 27017
      Mongo__Database: admin
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:4.2
    networks:
     - loki
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  loki:
    image: grafana/loki:2.8.2
    ports:
      - 3100:3100
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    networks:
      - loki
  
  promtail:
    image: grafana/promtail:2.8.2
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - "./promtail/config.yaml:/etc/promtail/config.yml"
      - "./logs/api:/logs/api"
      - "./tmp:/tmp"
    networks:
      - loki
    ports:
      - 9080:9080
